### PR TITLE
set new version of tomcat (8.5.8) and ecj (4.6.1)

### PR DESCRIPTION
**Pull request by tcollignon**
Hello,

If you think to make a 2.X version of this plugin (see #2), maybe it's time to upgrade Tomcat and ecj version.
As you want..

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Hi Thomas,

thanks so much for your pull requests. I've merged them all in and released version 2.0.0 of the plugin (the Maven search index isn't updated yet as of writing this). Since I don't work at mytoys.de anymore I changed the group ID to `io.leonard`.

I haven't been working with JSPs for over 5 years so I didn't really have a chance to test that the plugin still works. Would you mind trying it out on one of your projects?

Also, since my knowledge of JSPs is now severely outdated, I would like to ask if you'd be interested in becoming the maintainer of the project.

Again, thanks for your contribution.

Leonard

**Comment by tcollignon** [comment]
Hi Leonard,

Thanks you so much for merging it, I don't really think it when I submit this PR :)

You are lucky to not working with JSP now :)

Yes I'm ok to be the new maintainer, thank you. We will work with JSP in my society for long time I think, so I will use this plugin again. I'm currently run it with those PR, so I can tell you the 2.0.0 version works well, and fast.

**Comment by tcollignon** [comment]
Oh I just see you push some commits, so OK I will test official 2.0.0 version and let you know

**Comment by tcollignon** [comment]
Hi Leonard,

I remember this discussion, do you still want me to maintain this project?

**Comment by leonardehrenfried** [comment]
Yes, please. That would be great!

**Comment by tcollignon** [comment]
Ok cool !
Does I need some particular acces? I will mail you directly
thanks

**Pull request merged**
