### PR TITLE
Add plugin goals back to the generated site.

### PR DESCRIPTION
**Pull request by jpmsilva**
Also added an index page, which I did not see in the generated site when I tested locally.

### CODE REVIEW

**Comment by jpmsilva** [comment]
Apparently, after some version that I was unable to determine, maven-plugin-plugin stopped performing reporting duties for the site generation, being replaced by maven-plugin-report-plugin.
If you check the maven-plugin-plugin [documentation](https://maven.apache.org/plugin-tools/maven-plugin-plugin/usage.html), if you navigate to the page "Configuring Generation of Plugin Documentation" you are taken to the documentation of maven-plugin-report-plugin. And as far as I was able to determine, this was the only hint to the change I could find.

The [Plugin documentation guide](https://maven.apache.org/guides/development/guide-plugin-documentation.html#plugin-configuration-parameters) also confirms that maven-plugin-report-plugin is the plugin to use to generate the goals documentation. So I replaced one with the other.

I also added the index page to the site reports, which I think was missing.

Do let me know if any further clarification is required.

**Comment by jpmsilva** [comment]
Please don't merge this yet, as I think the navigation sidebar is lacking a link to the mojo documentation.
I'll try to add that as well.

**Comment by jpmsilva** [comment]
So, to summarize: this PR fixes the site generation by upgrading the site plugin descriptor and related reporting plugins.
I also added some pages to the documentation site, based on the repository README.md file and fixed the license URL (https is required to properly render the license text).

Since the dependency ecj has relocated to the groupId org.eclipse.jdt I changed those references. tomcat-jasper 10, which this plugin is referencing, is also pulling from org.eclipse.jdt:ecj. I did not find any need to override the version being pulled by tomcat-jasper, especially because the newest version no longer supports Java 11, so I decided to stick with the version being pulled by tomcat-jasper (3.33.0). People that wish to generate bytecode for newer JVMs can override the ECJ version, and I added that information to the howto page on the documentation site.

Should be good to go now!

**Comment by leonardehrenfried** [comment]
Thanks for this. The website is updated.

I actually haven't used JSPs since 2011 so I rely on outside contributors to keep this project alive. Are you interested in helping out maintaining it?

**Comment by jpmsilva** [comment]
Hi @leonardehrenfried 
I'm not entirely sure what the maintenance burden currently is for this project, but I can try to help out time permitting.

I took a quick look at the issue and PR queue, but I don't see any major pending matters.
Documentation could probably be polished a bit, and there are code adjustments and cleanups that can be applied (mostly due to the baseline JVM version now being JVM 11).
#44 seems to be interesting, but overall it can be worked around by manually setting/adding `**/*.jspf` to the `excludes` parameter (which is what the PR does transparently).

Anything major you think needs to be tackled?

On a separate note, I think that with #211 being merged, #24 can probably be closed as complete.

**Comment by jpmsilva** [comment]
Also, it would appear that the [GitHub releases page](https://github.com/leonardehrenfried/jspc-maven-plugin/releases) is not showing the newer versions. I'm not sure how you were managing this before... I can't find any hints related to this in the master branch.

**Comment by leonardehrenfried** [comment]
@tcollignon , who was previously the co-maintained, created the releases manually. There is probably a github action that can do it automatically. 

That's also something you can do, if you are interested.

**Pull request merged**
