### PR TITLE
add test to cover the case of using maven depencency 2.8 and maven 3.3.9

### PR DESCRIPTION
**Pull request by tcollignon**
For now I have just add a test, I haven't fix, I want to see if travis show the error

### CODE REVIEW

**Comment by tcollignon** [comment]
It's OK, Travis fail, so the bug is catched by IT

**Comment by leonardehrenfried** [comment]
Do you want me to merge this in, or do you want to fix the problem first?

**Comment by tcollignon** [comment]
I will fix this

**Comment by tcollignon** [comment]
I found the problem and my apologies it's not your change about maven release plugin but mine of upgrading maven version in plugin dependencies here a4087f366c to allow maven test harness to work correctly. I've downgrading it to 3.3.9 without any problem with maven test harness so everything will be fine noramally now

**Comment by leonardehrenfried** [comment]
Fantastic detective work.

**Comment by leonardehrenfried** [comment]
2.4.4 has been released.

**Pull request merged**
