### PR TITLE
add extra parameter to generate strings as char arrays

### PR DESCRIPTION
**Pull request by abendt**
we added an option to enable

genStringAsCharArray - Should text strings be generated as char arrays, to improve performance in some cases? Default false.

 http://tomcat.apache.org/tomcat-8.0-doc/jasper-howto.html

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This conflicts with your other PR. Can you resolve the conflicts, please?

**Comment by abendt** [comment]
should be fine now. the travis build failed, seems not to be related to my change?

**Comment by leonardehrenfried** [comment]
Thanks.

I just added travis builds an hour ago and yours is actually the very first build. I will take care of it.

**Comment by leonardehrenfried** [comment]
Version 2.2.0 has been released and is on its way to Maven Central.

**Pull request merged**
