### PR TITLE
Add parameter strictQuoteEscaping

### PR DESCRIPTION
**Pull request by kgb-financial-com**
This pull request is similar to https://github.com/leonardehrenfried/jspc-maven-plugin/pull/43 , but includes test cases.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
I'd say that this is pretty nice, @tcollignon. What do you think?

**Comment by leonardehrenfried** [comment]
Thanks for this pull request! Releasing a new version now...

**Comment by leonardehrenfried** [comment]
Version 3.1.1 has the fix.

**Comment by kgb-financial-com** [comment]
Thanks for the release, it works well!

**Comment by tcollignon** [comment]
Hi @leonardehrenfried ,

sorry for delay, no time this moment

Tx you to take care of the news coming in your project

And tx you @kgb-financial-com  to this commit with tests, it's really great

have a nice day both of you

**Pull request merged**
