### PR TITLE
Add options to allow skipping xsd validation, and to add http proxy i…

### PR DESCRIPTION
**Pull request by tcollignon**
…f needed

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Do you want an RC3?

**Comment by tcollignon** [comment]
Hi,

Yes please (but I think its rc4 :) )

**Comment by tcollignon** [comment]
Hi @leonardehrenfried , thx for the release

I notice that the site is not updated in RC4 version, car you check that please?

**Comment by leonardehrenfried** [comment]
Good catch, I had not thought about it.

It’s updated now.

On 12 November 2018 at 13:41:33, COLLIGNON Thomas (notifications@github.com)
wrote:

Hi @leonardehrenfried <https://github.com/leonardehrenfried> , thx for the
release

I notice that the site is not updated in RC4 version, car you check that
please?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/leonardehrenfried/jspc-maven-plugin/pull/35#issuecomment-437865297>,
or mute the thread

**Pull request merged**
