### PR TITLE
Update dependencies to last version

### PR DESCRIPTION
**Pull request by tcollignon**
So this is the PR for issue #12 
However I think it's too early to merge it because : 
- it contains jasper 9.0.1, and it still on beta 
- due to jasper 9.0.1 it break backward compatibility with old jasper version because of the new enum *TrimSpacesOption* introduce in jasper 9. So this version of the plugin will only work with jasper >=9.

It contains update of all dependencies, and plugin in version release (not alpha, beta or something similar, except for jasper)
It contains migration to JDK 1.8
It contains using of maven fluido skin in maven site :)

WDYT about this ?

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
An excellent PR, thanks!

I took a quick look and couldn't find anything about Jasper 9.0.1 being beta. Can you provide more information?

Also, since you've wrapped the trimSpaces option, for the user of the plugin this _is_ backwards compatible, isn't it? They won't have to update their configuration, correct?

The Java 8 requirement _is_ new but I guess adding a section to the Readme telling Java 7 users to use 2.4.1 should make this clear.

Also, predictably, the Java 7 build is failing. Can you remove it from .travis.yml?

**Comment by tcollignon** [comment]
Hi,

In fact this is tomcat 9 in beta => https://tomcat.apache.org/download-90.cgi , so I think jasper is in beta too
=> This PR let this plugin compatible with Tomcat 9 !
We can merge the PR, but I think the 3.0.0 release must waiting tomcat 9 release, are you agree with this?

Yes I wrap TrimSpacesOption, but if the plugin is using with jasper 8.X it doesn't work :( (I try) If it using out of the box (with jasper 9) it work without changing configuration.

Yes in documentation we need to explain the different versions : 

* 2.X => Work with JDK >= 7, and compatible with Jasper 8.X not 9.X
* 3.X => Work with JDK >=8, and compatible with Jasper 9.X, not 8.X

And we maintain two branches

Yes I will update the PR to fix travis configuration.

And I need to do more test. I think about added automated IT test too, if I have the time...

**Comment by leonardehrenfried** [comment]
I think most users will not care what specific version is used as long as it is compatible with their application server.

Is Jasper 9 compatible with Tomcat 8? Did something change in the JSP specification?

And is there a way in plugin to override which Jasper version is used that I'm not aware of?

**Comment by leonardehrenfried** [comment]
And I agree that we should wait until Tomcat 9 has a stable release.

**Comment by tcollignon** [comment]
Yes probably, but I don't think is a really good idea because differences exists between each version (I have seen major differences since tomcat 8.X)
Tomcat 9 is for servlet 4.0 spec, but JSP spec hasn't change. So yes I think Jasper 9 is compatible with Tomcat 8. Maybe I need to test it to be sure

The way to override Jasper version is this (and I think we should document it, because I think is the good way to use the plugin without surprise)

```
           <plugin>
                    <groupId>io.leonard.maven.plugins</groupId>
                    <artifactId>jspc-maven-plugin</artifactId>
                    <version>3.0.0-SNAPSHOT</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.tomcat</groupId>
                            <artifactId>tomcat-jasper</artifactId>
                            <version>8.5.4</version>
                            <exclusions>
                                <exclusion>
                                    <groupId>org.eclipse.jdt.core.compiler</groupId>
                                    <artifactId>ecj</artifactId>
                                </exclusion>
                            </exclusions>
                        </dependency>

                        <dependency>
                            <groupId>org.eclipse.jdt.core.compiler</groupId>
                            <artifactId>ecj</artifactId>
                            <version>4.6.1</version>
                        </dependency>
                    </dependencies>
                </plugin>
```

**Comment by tcollignon** [comment]
I have look further in jasper and i find a way to not break compatibility with jasper 8, I will update the PR, it will be better for users

**Comment by tcollignon** [comment]
it doesn't work, other method that I found not exist in jasper 8 :(

**Comment by leonardehrenfried** [comment]
Ok, that sounds all very good. Thanks for explaining. (You probably could do a very ugly reflection hack to figure out if trim spaces is a boolean or an enum, but I don't think it's worth it either.)

Let me know when you want this PR merged. Afterwards I will release version 3.

**Comment by leonardehrenfried** [comment]
@tcollignon I just checked and it seems that Tomcat 9 is no longer beta: http://tomcat.apache.org/download-90.cgi

Am I seeing this right?

**Comment by tcollignon** [comment]
Hello,

Yes you are right, I have seen this on twitter yesterday too
I put this on my list :)

**Comment by tcollignon** [comment]
Hi,

I go on this previously work toadd Tomcat 9 compatibility.
I have updated this branch with master branch, so I fix new conflict
I manage again dependencies to remove unnecessary one
I add annotations in Mojo (thx @candrews in PR #26)

This PR is for a future 3.X version of the plugin so we need a 2.X branch.

I need to do more test about this PR before merging

**Comment by leonardehrenfried** [comment]
Let me know when you would like to merge this.

**Comment by tcollignon** [comment]
Hi @leonardehrenfried 

I have do more tests, and it's working in my uses cases.

So I have created the 2.X based on actually master, and now I think you can do : 

- Merge this PR on master
- Roll a 3.0.0 release

Thx you

**Comment by tcollignon** [comment]
Oh wait , I have some random problem with optimized parallel JDTCompiler with tomcat 9 . Can you release a 3.0.0.rc1 version instead of 3.0.0 please?

**Comment by leonardehrenfried** [comment]
Ok, 3.0.0-RC1 has been released.

**Comment by tcollignon** [comment]
Thx you

**Pull request merged**
