### PR TITLE
Throw an error if validateXmlContent of merged xml is not ok. Fix ParallelJDTCompiler with Tomcat 9. Remove jetty-util

### PR DESCRIPTION
**Pull request by tcollignon**

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Let me know when this is ready for merging.

**Comment by tcollignon** [comment]
Yes thx @leonardehrenfried 

I'm currently on an issue with tomcat 9 and merged xml files, I try to understand the problem

**Comment by tcollignon** [comment]
@leonardehrenfried , If travis passes, can you releases an RC3 please?

Thx you

**Comment by tcollignon** [comment]
And moreover to avoid disturbing you, can you give me access to deploy to maven central @leonardehrenfried  ?

**Comment by tcollignon** [comment]
Hey @leonardehrenfried wait for the release please

**Comment by leonardehrenfried** [comment]
@tcollignon Ok, will wait.

Unfortunately it isn't really possible to give access to Sonatype (which deploys to Maven Central) for a single project only for the entire account. That means that I can't sadly give you access unless you move the plugin into your own namespace, which is in essence a fork. Do you want to do that? It would be ok for me, since you have really been the main developer for a while.

On the other hand, I really don't mind cutting the occasional release since you already prepare everything so well.

**Pull request merged**
