### PR TITLE
#42 Added new config paramater strictQuoteEscaping

### PR DESCRIPTION
**Pull request by kapitanrum**

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This looks good to me. 

@tcollignon do you see a problem with merging this?

**Comment by tcollignon** [comment]
Hi
No time to check here for now 
Will better with a test but you can merge as is
Tx

**Comment by leonardehrenfried** [comment]
That's actually a really good point.

@kapitanrum Can you add a test? You can see how they work here: https://github.com/leonardehrenfried/jspc-maven-plugin/tree/master/src/test/java/io/leonard/maven/plugins/jspc

**Comment by tcollignon** [comment]
Hi @kapitanrum 

I add one in my last pr : #44 
Can you do the same for your  PR  please?

**Comment by leonardehrenfried** [comment]
Superseded by #45.

**Pull request closed without merging**
