### PR TITLE
fix issue #9 : add thread index in each webXmlFragment filename to de…

### PR DESCRIPTION
**Pull request by tcollignon**
…al with multithreading mode and prevent file overwriting before web.xml merging

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This is fantastic work @tcollignon!

How would @philflack best install this for testing? `mvn install`?

**Comment by tcollignon** [comment]
Yes mvn install and it can use the plugin locally with maven local repository

Note : I need to add  -Dgpg.skip=true locally, otherwise this plugin won't work , I don't know why :(  ,I have this error : 
```
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
```

**Comment by leonardehrenfried** [comment]
Ok, thanks for the tip! The errors are probably because of the GPG signing requirements of Maven Central.

Can you bump the version to 2.3.0-SNAPSHOT? It will make it easier for @philflack to install it.

**Comment by philflack** [comment]
Code looks good; I'll wait for the new version to test, last time I tried building locally it went very wrong.

**Comment by leonardehrenfried** [comment]
I've added a snapshot version 2.4.0-SNAPSHOT to the Sonatype repo.

@philflack Can you try it out? You can configure Sonatype snapshots like this: https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

**Comment by philflack** [comment]
Managed to install it locally (proxy denying access to the public sonatype repo), and it's working nicely.  Great job guys!

**Pull request merged**
